### ISSUE TITLE
mint.Canvas doesnt handle focus of itself, only children

### ISSUE THREAD

**Issue by dazKind** [snowkit/mint#30]
mint.Canvas doesnt react on mouseenter/leave due to the fact that it only checks its children for focus. While this makes sense for fullscreen GUIs, this fails when your canvas is only a small part of the screen or in my case a object in 3D space. 

Given the assumption that all controls behave the same a canvas should be able to emit signals on mouseenter/leave and focus itself when no topmost child is found.

What do you think?

**Comment by underscorediscovery** [comment]
I've made sure canvas gets `mouseleave` and `mouseenter` events for now. That should help in the mean time.

**Comment by underscorediscovery** [comment]
The clarity of null focus/marked nodes is important and the recursion bugs I had early on were a pain. The canvas gets the needed events still, but I'm not going to make it return itself as focused - controls have `ishovered` as well so you have enough information to go on I think, both events and state query!
