### ISSUE TITLE
mint.List children do not inherit clip_with if added after clip_with is set on the list

### ISSUE THREAD

**Issue by inucode** [snowkit/mint#36]
If `add_item` is used on a `mint.List` after its `clip_with` is set, the child added does not have its own `clip_with` set properly.

**Comment by underscorediscovery** [comment]
Can you please make a simple test case to debug? I think this might be resolved along the changes since but I can't tell specifically from the description. The best option is a simple reproducible using `tests/empty_luxe` and paste the code here. Thanks!

**Comment by underscorediscovery** [comment]
If this is still an issue, feel free to reopen.
