### ISSUE TITLE
Button event not trigger when child of Panel

### ISSUE THREAD

**Issue by MangelMaxime** [snowkit/mint#37]
Hi,
I am not sure if this is a bug or not. But if I add a button inside a panel then the button don't react to mouse input.
However, if I place it inside a window then it act correctly.

Is it the intended behavior ?

**Comment by underscorediscovery** [comment]
How did you add the child specifically?

**Comment by MangelMaxime** [comment]
I used this code :

```haxe
        _panel = new mint.Panel ({
            parent: canvas,
            name: 'panel1',
            x: 10, y: 100, w: 200, h: 200,
            options: {
                color: new Color().rgb(RefColor.CARROT),
            }
        });

        new mint.Button({
            parent: _panel,
            name: 'btn_index2',
            x: 10, y: 52, w: 60, h: 32,
            text: 'Index',
            text_size: 14,
            options: {
                label: { color: new Color().rgb(RefColor.CLOUDS)},
                color_hover: new Color().rgb(RefColor.AMETHYST)
            },
            onclick: function(e,c) { trace('clicked');}
        });
```

**Comment by Blist** [comment]
https://gist.github.com/Blist/e852d419c734418ff202

Is it a piece of code Who isolate the bug. The panel does not transmit its signals(click, focus, input) to these children. Works with the empty_luxe project.

**Comment by ImDeity** [comment]
Just to add a little info, I had a similar problem before with panels being the parent of an interactive element like Buttons and Sliders.

Parenting the interactive element to something other than a panel, like a Window, is the workaround I ended up using.

**Comment by underscorediscovery** [comment]
Thanks @Blist and @ImDeity, the isolated test is exactly all that is needed to fix bugs like this. It's probably something simple.

**Comment by underscorediscovery** [comment]
Ok I had a quick look, and my first guess was useful.

```
var panel = new mint.Panel({
          parent:canvas,
          name:"panel1",
          mouse_input: true,
          x:50, y:50, w:200, h:150
        });
```

Note the addition of **`mouse_input: true`** to the constructor for the Panel.
I can't remember off hand if the parent prevents children from receiving events explicitly or not, so I'll still have a closer look at the situation.

In the meantime enable mouse input on the panel and it should work.

**Comment by anissen** [comment]
It looks like this issue would be solved by https://github.com/snowkit/mint/pull/44
