### ISSUE TITLE
Allow controls to be created without having a canvas as parent

### ISSUE THREAD

**Issue by KeyMaster-** [snowkit/mint#42]
This would be useful if you don't have the parent you want for a control available at the time you are creating the control. 
Currently, if the parent specified at creation doesn't lead to the canvas, the constructor throws an error.

**Comment by underscorediscovery** [comment]
In the current model, the canvas is required for the explicit order of operations to exist for the rendering to be agnostic. Changing this will break that flexibility, so in this iteration it will be required for now. 

It may be something we can review later, but the library is designed to be canvas based and a control outside of the canvas is an anti-pattern. Thanks for the idea.
