### ISSUE TITLE
Calling Luxe.scene.empty() corrupts mint widgets

### ISSUE THREAD

**Issue by anissen** [snowkit/mint#45]
**Left:** Mint widgets working as intended. **Right:** After calling `Luxe.scene.empty()`.

![screen shot 2016-03-01 at 19 47 01](https://cloud.githubusercontent.com/assets/879967/13437867/adb53794-dfe6-11e5-84bc-ee714b25aed3.png) ![screen shot 2016-03-01 at 19 47 20](https://cloud.githubusercontent.com/assets/879967/13437868/b05aa970-dfe6-11e5-8683-b7c628924c49.png)

**Comment by underscorediscovery** [comment]
:cake:
