### ISSUE TITLE
Error compiling after adding missing headers.

### ISSUE THREAD

**Issue by f-rank** [snowkit/mint#60]
Getting:

Error: nanovg.c
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(275) : error C2275: 'NVGcompositeOperationState' : illegal use of this type as an expression
        c:\haxetoolkit\haxe\lib\linc_nanovg\git\lib\nanovg\src\nanovg.h(120) : see declaration of 'NVGcompositeOperationState'
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(275) : error C2146: syntax error : missing ';' before identifier 'state'
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(275) : error C2065: 'state' : undeclared identifier
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(276) : error C2065: 'state' : undeclared identifier
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(276) : error C2224: left of '.srcRGB' must have struct/union type
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(277) : error C2065: 'state' : undeclared identifier
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(277) : error C2224: left of '.dstRGB' must have struct/union type
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(278) : error C2065: 'state' : undeclared identifier
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(278) : error C2224: left of '.srcAlpha' must have struct/union type
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(279) : error C2065: 'state' : undeclared identifier
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(279) : error C2224: left of '.dstAlpha' must have struct/union type
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(280) : error C2065: 'state' : undeclared identifier
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(280) : error C2440: 'return' : cannot convert from 'int' to 'NVGcompositeOperationState'
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(1040) : error C2275: 'NVGstate' : illegal use of this type as an expression
        C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(89) : see declaration of 'NVGstate'
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(1040) : error C2065: 'state' : undeclared identifier
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(1041) : error C2065: 'state' : undeclared identifier
C:/HaxeToolkit/haxe/lib/linc_nanovg/git/lib/nanovg/src/nanovg.c(1041) : error C2223: left of '->compositeOperation' must point to struct/union

This is after adding Glew to the project.
Is there a prefered compiler for this ?

**Comment by underscorediscovery** [comment]
did you perhaps mean to file this on the [linc_nanovg](https://github.com/snowkit/linc_nanovg) repo? If you open it there we can look.
